# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(351, 238)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 40, 331, 141))
        self.stackedWidget.setObjectName("stackedWidget")
        self.stackedWidgetPage1 = QtWidgets.QWidget()
        self.stackedWidgetPage1.setObjectName("stackedWidgetPage1")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.stackedWidgetPage1)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 0, 271, 141))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radon_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.radon_button.setIconSize(QtCore.QSize(16, 16))
        self.radon_button.setAutoDefault(False)
        self.radon_button.setFlat(False)
        self.radon_button.setObjectName("radon_button")
        self.verticalLayout.addWidget(self.radon_button)
        self.mem_analyze_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.mem_analyze_button.setObjectName("mem_analyze_button")
        self.verticalLayout.addWidget(self.mem_analyze_button)
        self.mem_subtraction_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.mem_subtraction_button.setObjectName("mem_subtraction_button")
        self.verticalLayout.addWidget(self.mem_subtraction_button)
        self.micrograph_membrane_subtraction_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.micrograph_membrane_subtraction_pushButton.setObjectName("micrograph_membrane_subtraction_pushButton")
        self.verticalLayout.addWidget(self.micrograph_membrane_subtraction_pushButton)
        self.stackedWidget.addWidget(self.stackedWidgetPage1)
        self.stackedWidgetPage2 = QtWidgets.QWidget()
        self.stackedWidgetPage2.setObjectName("stackedWidgetPage2")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.stackedWidgetPage2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(30, 0, 271, 141))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.mem_analyze_bezier_button = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.mem_analyze_bezier_button.setObjectName("mem_analyze_bezier_button")
        self.verticalLayout_2.addWidget(self.mem_analyze_bezier_button)
        self.mem_subtraction_bezier_button = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.mem_subtraction_bezier_button.setObjectName("mem_subtraction_bezier_button")
        self.verticalLayout_2.addWidget(self.mem_subtraction_bezier_button)
        self.micrograph_membrane_subtraction_bezier_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.micrograph_membrane_subtraction_bezier_pushButton.setObjectName("micrograph_membrane_subtraction_bezier_pushButton")
        self.verticalLayout_2.addWidget(self.micrograph_membrane_subtraction_bezier_pushButton)
        self.stackedWidget.addWidget(self.stackedWidgetPage2)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 41, 16))
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(60, 10, 103, 21))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 351, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.comboBox.currentIndexChanged['int'].connect(self.stackedWidget.setCurrentIndex) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MemXTerminator"))
        self.radon_button.setText(_translate("MainWindow", "Radon Analysis Blinking"))
        self.mem_analyze_button.setText(_translate("MainWindow", "Membrane Analyzer"))
        self.mem_subtraction_button.setText(_translate("MainWindow", "Particles Membrane Subtraction"))
        self.micrograph_membrane_subtraction_pushButton.setText(_translate("MainWindow", "Micrographs Membrane Subtraction"))
        self.mem_analyze_bezier_button.setText(_translate("MainWindow", "Membrane Analyzer"))
        self.mem_subtraction_bezier_button.setText(_translate("MainWindow", "Particles Membrane Subtraction"))
        self.micrograph_membrane_subtraction_bezier_pushButton.setText(_translate("MainWindow", "Micrographs Membrane Subtraction"))
        self.label.setText(_translate("MainWindow", "Mode:"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Radonfit"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Bezierfit"))

