# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MicrographMembraneSubtraction_Bezierfit.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MicrographMembraneSubtraction_Bezierfit(object):
    def setupUi(self, MicrographMembraneSubtraction_Bezierfit):
        MicrographMembraneSubtraction_Bezierfit.setObjectName("MicrographMembraneSubtraction_Bezierfit")
        MicrographMembraneSubtraction_Bezierfit.resize(622, 332)
        self.horizontalLayoutWidget = QtWidgets.QWidget(MicrographMembraneSubtraction_Bezierfit)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 11, 601, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.particle_label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.particle_label_3.setObjectName("particle_label_3")
        self.horizontalLayout_5.addWidget(self.particle_label_3)
        self.particle_lineEdit_3 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.particle_lineEdit_3.setObjectName("particle_lineEdit_3")
        self.horizontalLayout_5.addWidget(self.particle_lineEdit_3)
        self.particle_browse_pushButton_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.particle_browse_pushButton_3.setObjectName("particle_browse_pushButton_3")
        self.horizontalLayout_5.addWidget(self.particle_browse_pushButton_3)
        self.LOG_label = QtWidgets.QLabel(MicrographMembraneSubtraction_Bezierfit)
        self.LOG_label.setGeometry(QtCore.QRect(300, 151, 31, 16))
        self.LOG_label.setObjectName("LOG_label")
        self.LOG_textBrowser = QtWidgets.QTextBrowser(MicrographMembraneSubtraction_Bezierfit)
        self.LOG_textBrowser.setGeometry(QtCore.QRect(10, 171, 601, 151))
        self.LOG_textBrowser.setObjectName("LOG_textBrowser")
        self.gridLayoutWidget = QtWidgets.QWidget(MicrographMembraneSubtraction_Bezierfit)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 61, 601, 41))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.cpus_lineEdit_3 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.cpus_lineEdit_3.setObjectName("cpus_lineEdit_3")
        self.gridLayout_3.addWidget(self.cpus_lineEdit_3, 0, 1, 1, 1)
        self.cpus_label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.cpus_label_3.setObjectName("cpus_label_3")
        self.gridLayout_3.addWidget(self.cpus_label_3, 0, 0, 1, 1)
        self.batch_size_label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.batch_size_label_3.setObjectName("batch_size_label_3")
        self.gridLayout_3.addWidget(self.batch_size_label_3, 0, 2, 1, 1)
        self.batch_size_lineEdit_3 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.batch_size_lineEdit_3.setObjectName("batch_size_lineEdit_3")
        self.gridLayout_3.addWidget(self.batch_size_lineEdit_3, 0, 3, 1, 1)
        self.line = QtWidgets.QFrame(MicrographMembraneSubtraction_Bezierfit)
        self.line.setGeometry(QtCore.QRect(10, 141, 601, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(MicrographMembraneSubtraction_Bezierfit)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 110, 601, 32))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.kill_pushButton_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.kill_pushButton_3.setObjectName("kill_pushButton_3")
        self.horizontalLayout_6.addWidget(self.kill_pushButton_3)
        self.launch_pushButton_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.launch_pushButton_3.setObjectName("launch_pushButton_3")
        self.horizontalLayout_6.addWidget(self.launch_pushButton_3)

        self.retranslateUi(MicrographMembraneSubtraction_Bezierfit)
        QtCore.QMetaObject.connectSlotsByName(MicrographMembraneSubtraction_Bezierfit)

    def retranslateUi(self, MicrographMembraneSubtraction_Bezierfit):
        _translate = QtCore.QCoreApplication.translate
        MicrographMembraneSubtraction_Bezierfit.setWindowTitle(_translate("MicrographMembraneSubtraction_Bezierfit", "Micrograph Membrane Subtraction - Bezierfit - MemXTerminator"))
        self.particle_label_3.setText(_translate("MicrographMembraneSubtraction_Bezierfit", "Particle .cs file"))
        self.particle_browse_pushButton_3.setText(_translate("MicrographMembraneSubtraction_Bezierfit", "Browse..."))
        self.LOG_label.setText(_translate("MicrographMembraneSubtraction_Bezierfit", "LOG"))
        self.cpus_lineEdit_3.setText(_translate("MicrographMembraneSubtraction_Bezierfit", "15"))
        self.cpus_label_3.setText(_translate("MicrographMembraneSubtraction_Bezierfit", "Cpus"))
        self.batch_size_label_3.setText(_translate("MicrographMembraneSubtraction_Bezierfit", "Batch size"))
        self.batch_size_lineEdit_3.setText(_translate("MicrographMembraneSubtraction_Bezierfit", "30"))
        self.kill_pushButton_3.setText(_translate("MicrographMembraneSubtraction_Bezierfit", "Kill"))
        self.launch_pushButton_3.setText(_translate("MicrographMembraneSubtraction_Bezierfit", "Launch"))
